apt install apt
apt install bc
apt install bash
apt install zip
apt install dash
apt install dpkg
apt install gpgv
apt install libbz2
apt install libc++
apt install libcurl
apt install libgcrypt
apt install curl
apt install game-repo
apt install libiconv
apt install liblzma
apt install libnghttp2
apt install ncurses
apt install openssl
apt install readline
apt install scienc-repo
apt install termux-am
apt install termux-exec
apt install termux-keyring
apt install termux-licenses
apt install termux-tools
apt install zlib
apt install tmuxpt
apt install python
apt install python2
apt install git
apt install wget
apt install w3m
apt install perl
apt install clang
apt install curl
apt install make
apt install openssl-tool
apt install util-linux
apt install nano
apt install ruby
apt install hydra
apt install moon-buggy
apt install texinfo
apt install dnsutils
apt install netcat
apt install nmap
apt install vim
apt install grep
apt install cowsay
apt install toilet
gem install lolcat
apt-get install git
apt install neofetch
apt install gnupg
apt install libgpg-error
apt install ncurses-utils
apt install command-not-found
apt install libandroid-support
pkg install git
apt install ca-certificates
pkg install ruby
pkg install python2
pip2 install requests
pip2 install bs4
pip2 install mechanize
pip2 install beautifulsoup4
pip2 install dnspython
pip2 install scapy
pip2 install selenium
pip2 install colorama
pip2 install oauth2
pip2 install Flask-OAUth
pip2 install requests pexpect passlib
pip2 install rsa
pip2 install gtts
pip2 install lxml
pip2 install googletrans
pip2 install django-social-auth
pip2 install Facebook-WebBot
pip2 install fbchat
pip2 install Whatportis
pip install pinax-stripe
pip install pinax-messages
pip install selenium

