apt update -y
apt upgrade -y
apt install bc -y
apt install apt -y
apt install vim -y
apt install zip -y
apt install git -y
apt install w3m -y
apt install nano -y
apt install ruby -y
apt install curl -y
apt install make -y
apt install nmap -y
apt install grep -y
apt install perl -y
apt install curl -y
apt install make -y
apt install gpgv -y
apt install bash -y
apt install dash -y
apt install dpkg -y
apt install zlib -y
apt install wget -y
apt install unzip -y
apt install clang -y
apt install hydra -y
apt install gnupg -y
apt install netcat -y
apt install cowsay -y
apt install toilet -y
apt install libbz2 -y
apt install libc++ -y
apt install python -y
apt install texinfo -y
apt install libcurl -y
apt install ncurses -y
apt install openssl -y
apt install openssl-tool -y
apt install liblzma -y
apt install python2 -y
apt install python-dev -y
apt install libiconv -y
apt install neofetch -y
apt install dnsutils -y
apt install readline -y
apt install libgcrypt -y
apt install termux-am -y
apt install game-repo -y
apt install util-linux -y
apt install moon-buggy -y
apt install libnghttp2 -y
apt install termux-exec -y
apt install openssl-tool -y
apt install termux-tools -y
apt install libgpg-error -y
apt install ncurses-utils -y
apt install termux-keyring -y
apt install ca-certificates -y
apt install termux-licenses -y
pkg install ncurses-utils -y
apt install command-not-found -y
apt install libandroid-support -y
gem install lolcat -y
pkg update -y
pkg upgrade -y
pkg install tsu -y
pkg install bash -y
pkg install libcurl -y
pkg install php -y
pkg install ruby -y
pkg install python -y
pkg install python2 -y
pkg install openssh -y
pkg install figlet -y
pip insyall pint -y
pip2 install bs4 -y
pip2 install rsa -y
pip2 install gtts -y
pip2 install scapy -y
pip2 install fbchat -y
pip2 install oauth2 -y
pip2 install requests -y
pip2 install colorama -y
pip2 install selenium -y
pip2 install mechanize -y
pip2 install dnspython -y
pip2 install Whatportis -y
pip2 install Flask-OAUth -y
pip install pinax-stripe -y
pip2 install googletrans -y
pip install ncurses-utils -y
pip install pinax-messages -y
pip2 install beautifulsoup4 -y
pip2 install django-social-auth -y
pip2 install requests pexpect passlib -y
git clone https://gitlab.com/st42/termux-sudo
cd termux-sudo
cp sudo /data/data/com.termux/files/usr/bin
cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 700 /data/data/com.termux/files/usr/bin/sudo
